version: "3.7"

services:  
  backend:
    container_name: mynestapp
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - db
    ports:
      - ${APP_PORT}:3000
    # I have to create a docker network for this to work
    extra_hosts:
    - "dockerhost:$DOCKERHOST"
  db:
    image: mariadb:10.4
    container_name: mariadbnest
    env_file: ./.env
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_DATABASE: ${DB_NAME_DEVELOPMENT}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
volumes:
  db_data: